# Conexión a PostgreSQL (Supabase - pooler, modo transacción)
spring.datasource.url=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.wyewdagpmbaqgqpdpkab
spring.datasource.password=Ch-61087899
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.data-source-properties.prepareThreshold=0

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

jwt.secret=8f3Kx9mQzT2vL6pR4nW7yB1cJ5hN0sU3aE8dG2fH6iM9oP4rX7tZ1vY5wC0lQ3nK
jwt.expiration=86400000